augment: false
batch_size: 1
cfg: cfg/yolor_csp.cfg
conf_thres: 0.25
data: data/coco.yaml
device: '0'
exist_ok: false
img_size: 640
iou_thres: 0.65
name: exp
names: data/coco.names
project: runs/test
save_conf: false
save_json: true
save_txt: false
single_cls: false
task: val
verbose: false
weights: models/yolor_csp.pt
